CREATE TABLE USER (
  ID INTEGER NOT NULL,
  USERNAME VARCHAR NOT NULL,
  PASSWORD VARCHAR NOT NULL,
  CONSTRAINT USER_PK PRIMARY KEY ("ID"),
  CONSTRAINT USER_UQ UNIQUE ("USERNAME")
);

CREATE TABLE BOOK (
  ID INTEGER NOT NULL,
  NAME VARCHAR NOT NULL ,
  PRICE VARCHAR NOT NULL,
  AUTHOR VARCHAR NOT NULL,
  CONSTRAINT BOOK_PK PRIMARY KEY ("ID"),
  CONSTRAINT BOOK_UQ UNIQUE ("NAME")
);


INSERT INTO USER VALUES(1, 'admin', '123456');
INSERT INTO USER VALUES(2, 'san', '123456');
INSERT INTO USER VALUES(3, 'aragaki', '123456');


INSERT INTO BOOK VALUES(1, 'To kill the mocking bird', '100', 'Harper Lee');
INSERT INTO BOOK VALUES(2, 'One Flew Over the Cuckoo''s Nest ', '105', 'Ken Kesey');
INSERT INTO BOOK VALUES(3, 'My Summer Of Love', '110', 'Helen Cross');