
package com.san.calculator;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "Calculator", targetNamespace = "http://www.san.com/calculator")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Calculator {


    /**
     * 
     * @param parameters
     * @return
     *     returns com.san.calculator.AddNumbersResponse
     */
    @WebMethod(action = "urn:Add")
    @WebResult(name = "addNumbersResponse", targetNamespace = "http://www.san.com/calculator", partName = "parameters")
    public AddNumbersResponse addNumbers(
        @WebParam(name = "addNumbers", targetNamespace = "http://www.san.com/calculator", partName = "parameters")
        AddNumbers parameters);

}
